name: Fisrt Workflow
on: workflow_dispatch
jobs: 
  fisrt-job:
     runs-on: ubuntu-latest
     steps:
      - name: Print Greeting
      - run: echo "Greeting"
      - name: Print GoodBye
      - run: echo "Done - Bye"
